feat(containerfile): add containerfile for easy deployment
dohq/dockerhub_ratelimit_exporter pull request #4
Opened 2021-03-22 20:37 UTC by k3rnelpan1c-dev

### Description

Planed to offer you a PR for a Containerfile much earlier (sorry), however here we go.
This PR adds a basic Containerfile that can be used to package the exporter and run it on any Container Host (Docker, Podman, K8s, ...).
I left out the CI, as I was not sure how you would like to handle that (AFAIK goreleaser can package into Container Images as well).

Any feedback and question are very welcome.

### Changes

* Adds a basic Containerfile (with entrypoint script)
* Adds Containerfile documentation
* Change to bind to to any address per default (needed for containerfile)

### Issues

* n/a

2021-03-23 21:20 UTC, dohq requested changes
* Rename the file to Dockerfile?
* Put Dockerfile and entorypoint.sh in the root?(This is to make it easier to build container images.)

2021-03-24 02:22 UTC, dohq requested changes

2021-03-24 18:36 UTC, k3rnelpan1c-dev commented on container/Containerfile
> +FROM alpine:3.13
I can do that, however can you run bash scripts on `distroless`? If not you would loose the entrypoint script, as that requires bash in its current form.

2021-03-24 18:37 UTC, k3rnelpan1c-dev commented on container/Containerfile
> +COPY ./dockerhub_ratelimit_exporter /usr/local/bin
yeah sorry, that is a remains from my forks CI that I used to test this :sweat_smile: I'll fix it as soon as I can

2021-03-24 18:39 UTC, k3rnelpan1c-dev commented on README.md
> +`DH_PWD_FILE` | Mutual exclusive with the `DH_PWD` var, set to the path of a file containing the password/token of the `DH_USR`
sure can and will do!

2021-03-25 21:37 UTC, k3rnelpan1c-dev commented on container/Containerfile
> +FROM alpine:3.13
okay read up on the `distroless` base Image, and unless you want me to remove the entrypoint script and the functionality to allow for secrets (passwords) passed as files I would like to avoid that :confused: 

It is up to you, I can change it either way :wink:

2021-03-26 00:33 UTC, dohq commented on container/Containerfile
> +FROM alpine:3.13
Yeah, you right.
Let's leave the baseimage as alpine.

2021-03-27 07:01 UTC, dohq approved these changes

2021-03-27 07:02 UTC, dohq commented
I only moved the files here.
Thanks for the PR!
I'll merge them.

2021-03-27 07:02 UTC, merged

2021-03-27 15:46 UTC, k3rnelpan1c-dev commented
> I only moved the files here.
> Thanks for the PR!
> I'll merge them.

Yeah sorry intended to do that yesterday and forgot :sweat_smile: Thank you for the merge!